language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t brunocandia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true brunocandia/react-test npm run test

after_success:
  - docker build -t brunocandia/docker-multiple-container-fibonacci-client ./client
  - docker build -t brunocandia/docker-multiple-container-fibonacci-nginx ./nginx
  - docker build -t brunocandia/docker-multiple-container-fibonacci-server ./server
  - docker build -t brunocandia/docker-multiple-container-fibonacci-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push brunocandia/docker-multiple-container-fibonacci-client
  - docker push brunocandia/docker-multiple-container-fibonacci-nginx
  - docker push brunocandia/docker-multiple-container-fibonacci-server
  - docker push brunocandia/docker-multiple-container-fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-multiple-container"
  env: "DockerMultipleContainer-env"
  bucket_name: "elasticbeanstalk-us-east-2-463773643774"
  bucket_path: "docker-multiple-container"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
